# Autoload this script as 'NotificationUtil'

# Class-scoped notification constants
const NOTIFICATIONS_BY_CLASS = {
	"CanvasItem": {"NOTIFICATION_TRANSFORM_CHANGED": 2000, "NOTIFICATION_LOCAL_TRANSFORM_CHANGED": 35, "NOTIFICATION_DRAW": 30, "NOTIFICATION_VISIBILITY_CHANGED": 31, "NOTIFICATION_ENTER_CANVAS": 32, "NOTIFICATION_EXIT_CANVAS": 33, "NOTIFICATION_WORLD_2D_CHANGED": 36},
	"Container": {"NOTIFICATION_PRE_SORT_CHILDREN": 50, "NOTIFICATION_SORT_CHILDREN": 51},
	"Control": {"NOTIFICATION_RESIZED": 40, "NOTIFICATION_MOUSE_ENTER": 41, "NOTIFICATION_MOUSE_EXIT": 42, "NOTIFICATION_MOUSE_ENTER_SELF": 60, "NOTIFICATION_MOUSE_EXIT_SELF": 61, "NOTIFICATION_FOCUS_ENTER": 43, "NOTIFICATION_FOCUS_EXIT": 44, "NOTIFICATION_THEME_CHANGED": 45, "NOTIFICATION_SCROLL_BEGIN": 47, "NOTIFICATION_SCROLL_END": 48, "NOTIFICATION_LAYOUT_DIRECTION_CHANGED": 49},
	"EditorSettings": {"NOTIFICATION_EDITOR_SETTINGS_CHANGED": 10000},
	"MainLoop": {"NOTIFICATION_OS_MEMORY_WARNING": 2009, "NOTIFICATION_TRANSLATION_CHANGED": 2010, "NOTIFICATION_WM_ABOUT": 2011, "NOTIFICATION_CRASH": 2012, "NOTIFICATION_OS_IME_UPDATE": 2013, "NOTIFICATION_APPLICATION_RESUMED": 2014, "NOTIFICATION_APPLICATION_PAUSED": 2015, "NOTIFICATION_APPLICATION_FOCUS_IN": 2016, "NOTIFICATION_APPLICATION_FOCUS_OUT": 2017, "NOTIFICATION_TEXT_SERVER_CHANGED": 2018},
	"Node": {"NOTIFICATION_ENTER_TREE": 10, "NOTIFICATION_EXIT_TREE": 11, "NOTIFICATION_MOVED_IN_PARENT": 12, "NOTIFICATION_READY": 13, "NOTIFICATION_PAUSED": 14, "NOTIFICATION_UNPAUSED": 15, "NOTIFICATION_PHYSICS_PROCESS": 16, "NOTIFICATION_PROCESS": 17, "NOTIFICATION_PARENTED": 18, "NOTIFICATION_UNPARENTED": 19, "NOTIFICATION_SCENE_INSTANTIATED": 20, "NOTIFICATION_DRAG_BEGIN": 21, "NOTIFICATION_DRAG_END": 22, "NOTIFICATION_PATH_RENAMED": 23, "NOTIFICATION_CHILD_ORDER_CHANGED": 24, "NOTIFICATION_INTERNAL_PROCESS": 25, "NOTIFICATION_INTERNAL_PHYSICS_PROCESS": 26, "NOTIFICATION_POST_ENTER_TREE": 27, "NOTIFICATION_DISABLED": 28, "NOTIFICATION_ENABLED": 29, "NOTIFICATION_RESET_PHYSICS_INTERPOLATION": 2001, "NOTIFICATION_EDITOR_PRE_SAVE": 9001, "NOTIFICATION_EDITOR_POST_SAVE": 9002, "NOTIFICATION_WM_MOUSE_ENTER": 1002, "NOTIFICATION_WM_MOUSE_EXIT": 1003, "NOTIFICATION_WM_WINDOW_FOCUS_IN": 1004, "NOTIFICATION_WM_WINDOW_FOCUS_OUT": 1005, "NOTIFICATION_WM_CLOSE_REQUEST": 1006, "NOTIFICATION_WM_GO_BACK_REQUEST": 1007, "NOTIFICATION_WM_SIZE_CHANGED": 1008, "NOTIFICATION_WM_DPI_CHANGE": 1009, "NOTIFICATION_VP_MOUSE_ENTER": 1010, "NOTIFICATION_VP_MOUSE_EXIT": 1011, "NOTIFICATION_WM_POSITION_CHANGED": 1012, "NOTIFICATION_OS_MEMORY_WARNING": 2009, "NOTIFICATION_TRANSLATION_CHANGED": 2010, "NOTIFICATION_WM_ABOUT": 2011, "NOTIFICATION_CRASH": 2012, "NOTIFICATION_OS_IME_UPDATE": 2013, "NOTIFICATION_APPLICATION_RESUMED": 2014, "NOTIFICATION_APPLICATION_PAUSED": 2015, "NOTIFICATION_APPLICATION_FOCUS_IN": 2016, "NOTIFICATION_APPLICATION_FOCUS_OUT": 2017, "NOTIFICATION_TEXT_SERVER_CHANGED": 2018},
	"Node3D": {"NOTIFICATION_TRANSFORM_CHANGED": 2000, "NOTIFICATION_ENTER_WORLD": 41, "NOTIFICATION_EXIT_WORLD": 42, "NOTIFICATION_VISIBILITY_CHANGED": 43, "NOTIFICATION_LOCAL_TRANSFORM_CHANGED": 44},
	"Object": {"NOTIFICATION_POSTINITIALIZE": 0, "NOTIFICATION_PREDELETE": 1, "NOTIFICATION_EXTENSION_RELOADED": 2},
	"Skeleton3D": {"NOTIFICATION_UPDATE_SKELETON": 50},
	"Window": {"NOTIFICATION_VISIBILITY_CHANGED": 30, "NOTIFICATION_THEME_CHANGED": 32},
}

func get_notification_name(p_class_name: String, code: int) -> String:
	if p_class_name in NOTIFICATIONS_BY_CLASS:
		for name in NOTIFICATIONS_BY_CLASS[p_class_name].keys():
			if NOTIFICATIONS_BY_CLASS[p_class_name][name] == code:
				return name
	# Fallback search
	for cls in NOTIFICATIONS_BY_CLASS.keys():
		for name in NOTIFICATIONS_BY_CLASS[cls].keys():
			if NOTIFICATIONS_BY_CLASS[cls][name] == code:
				return name + " (from " + cls + ")"
	return "UNKNOWN_NOTIFICATION"

func get_notification_code(p_class_name: String, name: String) -> int:
	if p_class_name in NOTIFICATIONS_BY_CLASS and name in NOTIFICATIONS_BY_CLASS[p_class_name]:
		return NOTIFICATIONS_BY_CLASS[p_class_name][name]
	return -1

# Optional editor tool GUI can be implemented here.
# You could use this data to populate dropdowns or code completion.
# Example: provide a method that returns all notification names for a class.
func get_all_notifications_for_class(p_class_name: String) -> Array:
	if p_class_name in NOTIFICATIONS_BY_CLASS:
		return NOTIFICATIONS_BY_CLASS[p_class_name].keys()
	return []